name: Node CI

on: 
  push:
    branches:
      - master
  schedule:
    - cron: 0 2 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8, 10, 12]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test-dev
